/**
* helloworld API
* Helloworld Service
*
* OpenAPI spec version: 2.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/polycube-network/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */



#include "HelloworldJsonObject.h"
#include <regex>

namespace io {
namespace swagger {
namespace server {
namespace model {

HelloworldJsonObject::HelloworldJsonObject() :
  base_({}),
  m_portsIsSet (false),
  m_action (HelloworldActionEnum::DROP),
  m_actionIsSet (true) { }

HelloworldJsonObject::HelloworldJsonObject(nlohmann::json& val) :
  base_(val),
  m_portsIsSet (false),
  // Item with a default value, granted to be part of the request body
  m_action (string_to_HelloworldActionEnum(val.at("action").get<std::string>())),
  m_actionIsSet (true) {

  m_ports.clear();
  for (auto& item : val["ports"]) {
    PortsJsonObject newItem { item };
    m_ports.push_back(newItem);
  }
  m_portsIsSet = !m_ports.empty();
}

std::string HelloworldJsonObject::getName() const {
  return m_name;
}

void HelloworldJsonObject::setName(std::string value) {
  m_name = value;
  m_nameIsSet = true;
}

bool HelloworldJsonObject::nameIsSet() const {
  return m_nameIsSet;
}

const nlohmann::json &HelloworldJsonObject::getBase() const {
  return base_;
}

void HelloworldJsonObject::setBase(const nlohmann::json &base) {
  base_ = base;
}

nlohmann::json HelloworldJsonObject::toJson() const {
  nlohmann::json val;
  val.update(base_);

  {
    nlohmann::json jsonArray;
    for (auto& item : m_ports) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["ports"] = jsonArray;
    }
  }
  if (m_actionIsSet) {
    val["action"] = HelloworldActionEnum_to_string(m_action);
  }

  return val;
}

nlohmann::json HelloworldJsonObject::helpKeys() {
  nlohmann::json val = nlohmann::json::object();

  val["name"]["name"] = "name";
  val["name"]["type"] = "key";
  val["name"]["simpletype"] = "string";
  val["name"]["description"] = R"POLYCUBE(Name of the helloworld service)POLYCUBE";
  val["name"]["example"] = R"POLYCUBE(helloworld1)POLYCUBE";

  return val;
}

nlohmann::json HelloworldJsonObject::helpElements() {
  nlohmann::json val = nlohmann::json::object();

  val["uuid"]["name"] = "uuid";
  val["uuid"]["type"] = "leaf"; // Suppose that type is leaf
  val["uuid"]["simpletype"] = "string";
  val["uuid"]["description"] = R"POLYCUBE(UUID of the Cube)POLYCUBE";
  val["uuid"]["example"] = R"POLYCUBE()POLYCUBE";
  val["type"]["name"] = "type";
  val["type"]["type"] = "leaf"; // Suppose that type is leaf
  val["type"]["simpletype"] = "string";
  val["type"]["description"] = R"POLYCUBE(Type of the Cube (TC, XDP_SKB, XDP_DRV))POLYCUBE";
  val["type"]["example"] = R"POLYCUBE(TC)POLYCUBE";
  val["loglevel"]["name"] = "loglevel";
  val["loglevel"]["type"] = "leaf"; // Suppose that type is leaf
  val["loglevel"]["simpletype"] = "string";
  val["loglevel"]["description"] = R"POLYCUBE(Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE))POLYCUBE";
  val["loglevel"]["example"] = R"POLYCUBE(INFO)POLYCUBE";
  val["ports"]["name"] = "ports";
  val["ports"]["type"] = "leaf"; // Suppose that type is leaf
  val["ports"]["type"] = "list";
  val["ports"]["description"] = R"POLYCUBE(Entry of the ports table)POLYCUBE";
  val["ports"]["example"] = R"POLYCUBE()POLYCUBE";
  val["action"]["name"] = "action";
  val["action"]["type"] = "leaf"; // Suppose that type is leaf
  val["action"]["simpletype"] = "string";
  val["action"]["description"] = R"POLYCUBE(Action performed on the received packet (i.e., DROP, SLOWPATH, or FORWARD; default: DROP))POLYCUBE";
  val["action"]["example"] = R"POLYCUBE()POLYCUBE";

  return val;
}

nlohmann::json HelloworldJsonObject::helpWritableLeafs() {
  nlohmann::json val = nlohmann::json::object();

  val["loglevel"]["name"] = "loglevel";
  val["loglevel"]["simpletype"] = "string";
  val["loglevel"]["description"] = R"POLYCUBE(Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE))POLYCUBE";
  val["loglevel"]["example"] = R"POLYCUBE(INFO)POLYCUBE";
  val["action"]["name"] = "action";
  val["action"]["simpletype"] = "string";
  val["action"]["description"] = R"POLYCUBE(Action performed on the received packet (i.e., DROP, SLOWPATH, or FORWARD; default: DROP))POLYCUBE";
  val["action"]["example"] = R"POLYCUBE()POLYCUBE";

  return val;
}

nlohmann::json HelloworldJsonObject::helpComplexElements() {
  nlohmann::json val = nlohmann::json::object();

  val["ports"]["name"] = "ports";
  val["ports"]["type"] = "list";
  val["ports"]["description"] = R"POLYCUBE(Entry of the ports table)POLYCUBE";
  val["ports"]["example"] = R"POLYCUBE()POLYCUBE";

  return val;
}

std::vector<std::string> HelloworldJsonObject::helpActions() {
  std::vector<std::string> val;
  return val;
}

const std::vector<PortsJsonObject>& HelloworldJsonObject::getPorts() const{
  return m_ports;
}

void HelloworldJsonObject::addPorts(PortsJsonObject value) {
  m_ports.push_back(value);
}


bool HelloworldJsonObject::portsIsSet() const {
  return m_portsIsSet;
}

void HelloworldJsonObject::unsetPorts() {
  m_portsIsSet = false;
}



HelloworldActionEnum HelloworldJsonObject::getAction() const {
  return m_action;
}

void HelloworldJsonObject::setAction(HelloworldActionEnum value) {
  m_action = value;
  m_actionIsSet = true;
}

bool HelloworldJsonObject::actionIsSet() const {
  return m_actionIsSet;
}

void HelloworldJsonObject::unsetAction() {
  m_actionIsSet = false;
}

std::string HelloworldJsonObject::HelloworldActionEnum_to_string(const HelloworldActionEnum &value){
  switch(value){
    case HelloworldActionEnum::DROP:
      return std::string("drop");
    case HelloworldActionEnum::SLOWPATH:
      return std::string("slowpath");
    case HelloworldActionEnum::FORWARD:
      return std::string("forward");
    default:
      throw std::runtime_error("Bad Helloworld action");
  }
}

HelloworldActionEnum HelloworldJsonObject::string_to_HelloworldActionEnum(const std::string &str){
  if (JsonObjectBase::iequals("drop", str))
    return HelloworldActionEnum::DROP;
  if (JsonObjectBase::iequals("slowpath", str))
    return HelloworldActionEnum::SLOWPATH;
  if (JsonObjectBase::iequals("forward", str))
    return HelloworldActionEnum::FORWARD;
  throw std::runtime_error("Helloworld action is invalid");
}


}
}
}
}


